---
knowledge_base_settings:
  title: Ustawienia bazy wiedzy "Knowledge Base"
  0: >

knowledge_base_status:
  title: Status Baz Wiedzy
  content: >
    Włącz, aby pozwolić użytkownikom na samodzielną obsługę publicznych artykułów bazy wiedzy. <br><br> Kategorie bazy wiedzy oraz FAQ mogą być ustawione jako wewnętrzne (widoczne tylko dla przedstawicieli).
  links:
    - 
      title: Zarządzanie bazami wiedzy "Knowledge Base"
      href: /scp/kb.php
restrict_kb:
  title: Restrict Access to the Knowledge Base
  content: >
    Włącz tą opcję żeby zapobiec dostępowi niezarejestrowanych użytkowników do artykułów w twojej bazy wiedzy za pomocą interface'u klienta.
  links:
    - 
      title: Ustawienia kontroli dostępu
      href: /scp/settings.php?t=users
canned_responses:
  title: Przygotowane odpowiedzi
  content: >
    Włącz, aby zezwolić przedstawicielom na używanie <span class="doc-desc-title">Przygotowanych odpowiedzi</span> w odpowiedziach na zgłoszenia.
  links:
    - 
      title: Zarządzaj Przygotowanymi Odpowiedziami
      href: /scp/canned.php
